### PR TITLE
Update README (fix to be usable)

### PR DESCRIPTION
**Pull request by Nephos**

### CODE REVIEW

**Comment by splattael** [comment]
@Nephos Thank you :green_heart: 

Please note that the example in README will change as the API changes! :-)

**Comment by Nephos** [comment]
Yes, I'm making [a wrapper](https://github.com/Nephos/notify) to handle that issue :)

**Comment by splattael** [comment]
@Nephos Be aware that I am planning to wrap the generated C glue code with a nice OO api similar to Ruby's version at https://github.com/splattael/libnotify

After this, your wrapper will be obsolete :warning: 

That said, I am happy to help you integrating your wrapper in code base `libnotify.cr` itself :smile:

**Comment by Nephos** [comment]
Looks like a new PR right ?

It seems that "timeout", "category", "urgency" and "close" are missing.

Do you want a hand to do the wrapper ?

**Pull request merged**
